import { SubNavbar } from "@/components/snavbar";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Recommend a Song - Staylist",
  description: "Generated by create next app",
};

export default function RecommendLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <>
      <SubNavbar />
      {children}
    </>
  );
}
